[package]
name = "wakaama-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cmake = "0.1.51"
bindgen = "0.70.1"

[dev-dependencies]
coap-lite = "0.13.0"

[dependencies]
lazy_static = "1.5.0"
